### ISSUE TITLE
Compression return values

### ISSUE THREAD

**Issue by dseuss** [dseuss/mpnum#3]
What should we return from compression procedures? Make sure that we don't too much waste time with computing information we don't always use!

**Comment by milan-hl** [comment]
Fixed in f11312d69a0bfa0eb163b4baf3fe99853cab728c...156fa0f64b1753875decdeadf5db40f1e924df35. We return the absolute overlap and let the user do anything else. We now provide an overview over what is possible in [the new docstring](http://mpnum.readthedocs.org/en/latest/mpnum.html#mpnum.mparray.MPArray.compress).
