### ISSUE TITLE
Normal form vs Normalized

### ISSUE THREAD

**Issue by dseuss** [dseuss/mpnum#31]
I am slowly getting angry with my past self for calling the cannoncial form as normal form (and, hence, introducing functions such as `MPArray.normalize(...)`. This will be a big change in the API, but I think we should think about a new naming scheme.

And while we are making ourselves unhappy, I would also think about renaming `bdims` to `ranks` and `pdims` to `dims`. I think the distinction would help readability a little

**Comment by milan-hl** [comment]
I think replacing our homegrown names with more commonly used names is a good thing. I think we should keep the old names as aliases to the new names for some time. The aliases could generate warnings if used. 

I am not so sure what names to choose, however. 

- `bdims` -> `ranks`: There seems no doubt about that one. One the other hand, should we make it `ttranks`?

- `pdims` -> `dims`: Some authors [1] say an array with d indices has dimension d, so this might be ambigous. [2] writes "tensor of size n_1 times n_2 ... n_d". The same authors refer to one index of the tensor as a mode and [1] also calls the n_k "mode sizes". We could change `pdims` to `mdims` or `msizes` or `mshapes` (numpy-style).  Strictly speaking, our "modes" maybe composed of multiple sub-modes but this works quite nicely because e.g. `msizes[0] = (2, 2)` would give a size tuple for the zeroth mode. 

- The number of indices of a tensor is called "dimension" or "order". Numpy calls it `ndim` ("[Number of array dimensions.](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html)")

- `plegs` -> `submodes` or `mndim`? 

- At the moment, we also have `dims` and `legs`: `dims` is "Tuple of shapes for the local tensors" and `legs` is the number of entries in these tuples. We could call them `coreshapes` and `corendim`. (Or maybe use something more consistent with the other decisions we make.) 

- Is the "dimension" or "order" of our tensor given by `len(mpa)` or by `np.prod(mpa.plegs)`? 

- Do you also want to rename other methods such as `bleg2pleg`, `pad_bdim`, `paxis_iter`?

[1] http://dx.doi.org/10.1137/090752286
[2] https://arxiv.org/abs/1302.7121

**Comment by dseuss** [comment]
Currently at it on the `refactor` branch. Let me know if you have any suggestions.

**Comment by dseuss** [comment]
There is one more thing that I find confusing: `outer` vs `louter`. How about:
- `outer` -> `kron` (because it acts similarly to `from_kron`) or `chain` 
- `louter` -> `outer` or `tensor`?

**Comment by milan-hl** [comment]
What about the wording for the documentation? `bond leg` becomes `virtual leg`? Do we keep the name `physical leg`?

**Comment by dseuss** [comment]
Yes, I think that's OK unless you have a better suggestion 

⁣Sent from TypeApp ​

**Comment by milan-hl** [comment]
Fixed in the refactor branch with fe3e95a8ce94741f87f38cf750f546dc07dc5bec and all the preceding commits.
